"""Add message_files table and permanent flag

Revision ID: 8f928dbf8482
Revises: deea166656d4
Create Date: 2025-05-13 16:55:21.087963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f928dbf8482'
down_revision: Union[str, None] = 'deea166656d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_files_file_id'), 'message_files', ['file_id'], unique=False)
    op.create_index(op.f('ix_message_files_id'), 'message_files', ['id'], unique=False)
    op.add_column('gemini_files', sa.Column('permanent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gemini_files', 'permanent')
    op.drop_index(op.f('ix_message_files_id'), table_name='message_files')
    op.drop_index(op.f('ix_message_files_file_id'), table_name='message_files')
    op.drop_table('message_files')
    # ### end Alembic commands ###
